Hooks.on('renderChatMessage', (app, html, data) => {
  replaceWordsInText(html);
});

function replaceWordsInText(element) {
  // Определите слова, которые вы хотите заменить и соответствующие им описания
  const wordMappings = {
    'аазимар': 'PF2E.TraitDescriptionAasimar',
    'преграждение': 'PF2E.TraitDescriptionAbjuration',
    'кислота': 'PF2E.TraitDescriptionAcid',
    'примесь': 'PF2E.TraitDescriptionAdditive',
    'примесь 0': 'PF2E.TraitDescriptionAdditive',
    'примесь 1': 'PF2E.TraitDescriptionAdditive',
    'примесь 2': 'PF2E.TraitDescriptionAdditive',
    'примесь 3': 'PF2E.TraitDescriptionAdditive',
    'примесь0': 'PF2E.TraitDescriptionAdditive',
    'примесь1': 'PF2E.TraitDescriptionAdditive',
    'примесь2': 'PF2E.TraitDescriptionAdditive',
    'примесь3': 'PF2E.TraitDescriptionAdditive',
    'примесь_0': 'PF2E.TraitDescriptionAdditive',
    'примесь_1': 'PF2E.TraitDescriptionAdditive',
    'примесь_2': 'PF2E.TraitDescriptionAdditive',
    'примесь_3': 'PF2E.TraitDescriptionAdditive',
    'Adjusted': 'PF2E.TraitDescriptionAdjusted',
    'приспособление': 'PF2E.TraitDescriptionAdjustment',
    'эон': 'PF2E.TraitDescriptionAeon',
    'асы': 'PF2E.TraitDescriptionAesir',
    'последствие': 'PF2E.TraitDescriptionAftermath',
    'агатион': 'PF2E.TraitDescriptionAgathion',
    'быстрое': 'PF2E.TraitDescriptionAgile',
    'воздух': 'PF2E.TraitDescriptionAir',
    'алхимический': 'PF2E.TraitDescriptionAlchemical',
    'алхимик': 'PF2E.TraitDescriptionAlchemist',
    'расширение': 'PF2E.TraitDescriptionAmp',
    'земноводный': 'PF2E.TraitDescriptionAmphibious',
    'анади': 'PF2E.TraitDescriptionAnadi',
    'андроид': 'PF2E.TraitDescriptionAndroid',
    'наивысший': 'PF2E.TraitDescriptionApex',
    'афорит': 'PF2E.TraitDescriptionAphorite',
    'Aquadynamic': 'PF2E.TraitDescriptionAquadynamic',
    'аркана': 'PF2E.TraitDescriptionArcane',
    'Ardande': 'PF2E.TraitDescriptionArdande',
    'архетип': 'PF2E.TraitDescriptionArchetype',
    'артефакт': 'PF2E.TraitDescriptionArtifact',
    'прикрепляемый': 'PF2E.TraitDescriptionAttached',
    'атака': 'PF2E.TraitDescriptionAttack',
    'слуховой': 'PF2E.TraitDescriptionAuditory',
    'аура': 'PF2E.TraitDescriptionAura',
    'автоматон': 'PF2E.TraitDescriptionAutomaton',
    'азаркети': 'PF2E.TraitDescriptionAzarketi',
    'предательское': 'PF2E.TraitDescriptionBackstabber',
    'обратный замах': 'PF2E.TraitDescriptionBackswing',
    'варвар': 'PF2E.TraitDescriptionBarbarian',
    'бард': 'PF2E.TraitDescriptionBard',
    'barding': 'PF2E.TraitDescriptionBarding',
    'зверолюди': 'PF2E.TraitDescriptionBeastkin',
    'бомба': 'PF2E.TraitDescriptionBomb',
    'bottled breath': 'PF2E.TraitDescriptionBottledBreath',
    'brace': 'PF2E.TraitDescriptionBrace',
    'брутальное': 'PF2E.TraitDescriptionBrutal',
    'защитный': 'PF2E.TraitDescriptionBulwark',
    'чары': 'PF2E.TraitDescriptionCantrip',
    'вместимость': 'PF2E.TraitDescriptionCapacity',
    'катализатор': 'PF2E.TraitDescriptionCatalyst',
    'коточеловек': 'PF2E.TraitDescriptionCatfolk',
    'чемпион': 'PF2E.TraitDescriptionChampion',
    'подменыш': 'PF2E.TraitDescriptionChangeling',
    'хаотичный': 'PF2E.TraitDescriptionChaotic',
    'жрец': 'PF2E.TraitDescriptionCleric',
    'карабканье': 'PF2E.TraitDescriptionClimbing',
    'заводной': 'PF2E.TraitDescriptionClockwork',
    'сварганенное': 'PF2E.TraitDescriptionCobbled',
    'coda': 'PF2E.TraitDescriptionCoda',
    'холод': 'PF2E.TraitDescriptionCold',
    'комбинированное': 'PF2E.TraitDescriptionCombination',
    'удобный': 'PF2E.TraitDescriptionComfort',
    'обычный': 'PF2E.TraitDescriptionCommon',
    'компаньон': 'PF2E.TraitDescriptionCompanion',
    'комплексная': 'PF2E.TraitDescriptionComplex',
    'составной': 'PF2E.TraitDescriptionComposite',
    'композиция': 'PF2E.TraitDescriptionComposition',
    'скрываемое': 'PF2E.TraitDescriptionConcealable',
    'концентрация': 'PF2E.TraitDescriptionConcentrate',
    'сотрясающее': 'PF2E.TraitDescriptionConcussive',
    'воплощение': 'PF2E.TraitDescriptionConjuration',
    'конрасу': 'PF2E.TraitDescriptionConrasu',
    'освящение': 'PF2E.TraitDescriptionConsecration',
    'конструкт': 'PF2E.TraitDescriptionConstruct',
    'расходуемый': 'PF2E.TraitDescriptionConsumable',
    'контакт': 'PF2E.TraitDescriptionContact',
    'сопряженность': 'PF2E.TraitDescriptionContingency',
    'контракт': 'PF2E.TraitDescriptionContract',
    'коатль': 'PF2E.TraitDescriptionCouatl',
    'критическое слияние': 'PF2E.TraitDescriptionCriticalFusion',
    'проклятие': 'PF2E.TraitDescriptionCurse',
    'оковы проклятия': 'PF2E.TraitDescriptionCursebound',
    'проклятый': 'PF2E.TraitDescriptionCursed',
    'дэймон': 'PF2E.TraitDescriptionDaemon',
    'тьма': 'PF2E.TraitDescriptionDarkness',
    'смертельное': 'PF2E.TraitDescriptionDeadly',
    'смертельное 2d10': 'PF2E.TraitDescriptionDeadly',
    'смертельное 2d12': 'PF2E.TraitDescriptionDeadly',
    'смертельное 2d8': 'PF2E.TraitDescriptionDeadly',
    'смертельное 3d10': 'PF2E.TraitDescriptionDeadly',
    'смертельное 3d12': 'PF2E.TraitDescriptionDeadly',
    'смертельное 3d8': 'PF2E.TraitDescriptionDeadly',
    'смертельное 4d10': 'PF2E.TraitDescriptionDeadly',
    'смертельное 4d12': 'PF2E.TraitDescriptionDeadly',
    'смертельное 4d8': 'PF2E.TraitDescriptionDeadly',
    'смертельное d10': 'PF2E.TraitDescriptionDeadly',
    'смертельное d12': 'PF2E.TraitDescriptionDeadly',
    'смертельное d4': 'PF2E.TraitDescriptionDeadly',
    'смертельное d6': 'PF2E.TraitDescriptionDeadly',
    'смертельное d8': 'PF2E.TraitDescriptionDeadly',
    'смерть': 'PF2E.TraitDescriptionDeath',
    'посвящение': 'PF2E.TraitDescriptionDedication',
    'censer': 'PF2E.TraitDescriptionCenser',
    'обнаружение': 'PF2E.TraitDescriptionDetection',
    'девиантный': 'PF2E.TraitDescriptionDeviant',
    'дампир': 'PF2E.TraitDescriptionDhampir',
    'разоружение': 'PF2E.TraitDescriptionDisarm',
    'болезнь': 'PF2E.TraitDescriptionDisease',
    'прорицание': 'PF2E.TraitDescriptionDivination',
    'сакральный': 'PF2E.TraitDescriptionDivine',
    'двуствольное': 'PF2E.TraitDescriptionDoubleBarrel',
    'отдых': 'PF2E.TraitDescriptionDowntime',
    'наркотик': 'PF2E.TraitDescriptionDrug',
    'друид': 'PF2E.TraitDescriptionDruid',
    'сумеречный': 'PF2E.TraitDescriptionDuskwalker',
    'дварф': 'PF2E.TraitDescriptionDwarf',
    'земля': 'PF2E.TraitDescriptionEarth',
    'эйдолон': 'PF2E.TraitDescriptionEidolon',
    'электричество': 'PF2E.TraitDescriptionElectricity',
    'эльф': 'PF2E.TraitDescriptionElf',
    'эликсир': 'PF2E.TraitDescriptionElixir',
    'эмоция': 'PF2E.TraitDescriptionEmotion',
    'очарование': 'PF2E.TraitDescriptionEnchantment',
    'entrench': 'PF2E.TraitDescriptionEntrench',
    'окружение': 'PF2E.TraitDescriptionEnvironment',
    'эзотерика': 'PF2E.TraitDescriptionEsoterica',
    'зло': 'PF2E.TraitDescriptionEvil',
    'эвокация': 'PF2E.TraitDescriptionEvocation',
    'эволюция': 'PF2E.TraitDescriptionEvolution',
    'expandable': 'PF2E.TraitDescriptionExpandable',
    'исследование': 'PF2E.TraitDescriptionExploration',
    'межпространственный': 'PF2E.TraitDescriptionExtradimensional',
    'фатальное': 'PF2E.TraitDescriptionFatal',
    'фатальное прицеливание': 'PF2E.TraitDescriptionFatalAim',
    'фатальное прицеливание d10': 'PF2E.TraitDescriptionFatalAim',
    'фатальное прицеливание d12': 'PF2E.TraitDescriptionFatalAim',
    'фатальное d10': 'PF2E.TraitDescriptionFatal',
    'фатальное d12': 'PF2E.TraitDescriptionFatal',
    'фатальное d8': 'PF2E.TraitDescriptionFatal',
    'страх': 'PF2E.TraitDescriptionFear',
    'фечлин': 'PF2E.TraitDescriptionFetchling',
    'фея': 'PF2E.TraitDescriptionFey',
    'бес/исчадие': 'PF2E.TraitDescriptionFiend',
    'бес': 'PF2E.TraitDescriptionFiend',
    'исчадие': 'PF2E.TraitDescriptionFiend',
    'воин': 'PF2E.TraitDescriptionFighter',
    'figurehead': 'PF2E.TraitDescriptionFigurehead',
    'точное': 'PF2E.TraitDescriptionFinesse',
    'финишер': 'PF2E.TraitDescriptionFinisher',
    'конечный': 'PF2E.TraitDescriptionFinite',
    'огонь': 'PF2E.TraitDescriptionFire',
    'флэшворп': 'PF2E.TraitDescriptionFleshwarp',
    'гибкий': 'PF2E.TraitDescriptionFlexible',
    'размах': 'PF2E.TraitDescriptionFlourish',
    'фокусирующий': 'PF2E.TraitDescriptionFocused',
    'foldaway': 'PF2E.TraitDescriptionFoldaway',
    'сила': 'PF2E.TraitDescriptionForce',
    'силовое': 'PF2E.TraitDescriptionForceful',
    'удача': 'PF2E.TraitDescriptionFortune',
    'свободная рука': 'PF2E.TraitDescriptionFreeHand',
    'фулу': 'PF2E.TraitDescriptionFulu',
    'грибковый': 'PF2E.TraitDescriptionFungus',
    'гаджет': 'PF2E.TraitDescriptionGadget',
    'ганзи': 'PF2E.TraitDescriptionGanzi',
    'общая': 'PF2E.TraitDescriptionGeneral',
    'гений': 'PF2E.TraitDescriptionGenie',
    'джинникин': 'PF2E.TraitDescriptionGeniekin',
    'горан': 'PF2E.TraitDescriptionGhoran',
    'привидение': 'PF2E.TraitDescriptionGhost',
    'упырь': 'PF2E.TraitDescriptionGhoul',
    'ghul': 'PF2E.TraitDescriptionGhul',
    'гигант': 'PF2E.TraitDescriptionGiant',
    'гнолл': 'PF2E.TraitDescriptionGnoll',
    'гном': 'PF2E.TraitDescriptionGnome',
    'гоблин': 'PF2E.TraitDescriptionGoblin',
    'голем': 'PF2E.TraitDescriptionGolem',
    'голома': 'PF2E.TraitDescriptionGoloma',
    'добро': 'PF2E.TraitDescriptionGood',
    'захват': 'PF2E.TraitDescriptionGrapple',
    'гремлин': 'PF2E.TraitDescriptionGremlin',
    'гримуар': 'PF2E.TraitDescriptionGrimoire',
    'гриот': 'PF2E.TraitDescriptionGrioth',
    'гриппли': 'PF2E.TraitDescriptionGrippli',
    'стрелок': 'PF2E.TraitDescriptionGunslinger',
    'полуэльф': 'PF2E.TraitDescriptionHalfElf',
    'полуорк': 'PF2E.TraitDescriptionHalfOrc',
    'полурослик': 'PF2E.TraitDescriptionHalfling',
    'мешающее': 'PF2E.TraitDescriptionHampering',
    'ханту': 'PF2E.TraitDescriptionHantu',
    'harnessed': 'PF2E.TraitDescriptionHarnessed',
    'harrow court': 'PF2E.TraitDescriptionHarrowCourt',
    'призрак': 'PF2E.TraitDescriptionHaunt',
    'исцеление': 'PF2E.TraitDescriptionHealing',
    'вестник': 'PF2E.TraitDescriptionHerald',
    'наследие': 'PF2E.TraitDescriptionHeritage',
    'сглаз': 'PF2E.TraitDescriptionHex',
    'hindering': 'PF2E.TraitDescriptionHindering',
    'хобгоблин': 'PF2E.TraitDescriptionHobgoblin',
    'человек': 'PF2E.TraitDescriptionHuman',
    'гуманоид': 'PF2E.TraitDescriptionHumanoid',
    'ифрит': 'PF2E.TraitDescriptionIfrit',
    'иллюзия': 'PF2E.TraitDescriptionIllusion',
    'импульс': 'PF2E.TraitDescriptionImpulse',
    'недееспособность': 'PF2E.TraitDescriptionIncapacitation',
    'инкарнация': 'PF2E.TraitDescriptionIncarnate',
    'бестелесный': 'PF2E.TraitDescriptionIncorporeal',
    'неминуемый': 'PF2E.TraitDescriptionInevitable',
    'насыщенный': 'PF2E.TraitDescriptionInfused',
    'нагнетание': 'PF2E.TraitDescriptionInfusion',
    'глотаемый': 'PF2E.TraitDescriptionIngested',
    'вдыхаемый': 'PF2E.TraitDescriptionInhaled',
    'инъекционный': 'PF2E.TraitDescriptionInjection',
    'ранение': 'PF2E.TraitDescriptionInjury',
    'inscribed': 'PF2E.TraitDescriptionInscribed',
    'integrated 1d6 b': 'PF2E.TraitDescriptionIntegrated',
    'integrated 1d6 p': 'PF2E.TraitDescriptionIntegrated',
    'integrated 1d6 s': 'PF2E.TraitDescriptionIntegrated',
    'integrated 1d6 s (versatile p)': 'PF2E.TraitDescriptionIntegrated',
    'разумный': 'PF2E.TraitDescriptionIntelligent',
    'взаимодействовать': 'PF2E.TraitDescriptionInteract',
    'изобретатель': 'PF2E.TraitDescriptionInventor',
    'инвестируемый': 'PF2E.TraitDescriptionInvested',
    'сыщик': 'PF2E.TraitDescriptionInvestigator',
    'кавалерийское': 'PF2E.TraitDescriptionJousting',
    'кайджу': 'PF2E.TraitDescriptionKaiju',
    'ками': 'PF2E.TraitDescriptionKami',
    'кашриши': 'PF2E.TraitDescriptionKashrishi',
    'отдача': 'PF2E.TraitDescriptionKickback',
    'кинетик': 'PF2E.TraitDescriptionKineticist',
    'кицунэ': 'PF2E.TraitDescriptionKitsune',
    'кобольд': 'PF2E.TraitDescriptionKobold',
    'ламинар': 'PF2E.TraitDescriptionLaminar',
    'launching': 'PF2E.TraitDescriptionLaunching',
    'принципиальный': 'PF2E.TraitDescriptionLawful',
    'леший': 'PF2E.TraitDescriptionLeshy',
    'свет': 'PF2E.TraitDescriptionLight',
    'языковой': 'PF2E.TraitDescriptionLinguistic',
    'литания': 'PF2E.TraitDescriptionLitany',
    'людоящер': 'PF2E.TraitDescriptionLizardfolk',
    'lozenge': 'PF2E.TraitDescriptionLozenge',
    'магический': 'PF2E.TraitDescriptionMagical',
    'магус': 'PF2E.TraitDescriptionMagus',
    'воздействие': 'PF2E.TraitDescriptionManipulate',
    'механический': 'PF2E.TraitDescriptionMechanical',
    'ментальный': 'PF2E.TraitDescriptionMental',
    'металл': 'PF2E.TraitDescriptionMetal',
    'метамагия': 'PF2E.TraitDescriptionMetamagic',
    'неразумный': 'PF2E.TraitDescriptionMindless',
    'сдвиг разума': 'PF2E.TraitDescriptionMindshift',
    'миньон': 'PF2E.TraitDescriptionMinion',
    'неудача': 'PF2E.TraitDescriptionMisfortune',
    'эффекты неудачи': 'PF2E.TraitDescriptionMisfortuneEffects',
    'missive': 'PF2E.TraitDescriptionMissive',
    'модификация': 'PF2E.TraitDescriptionModification',
    'модульное д, к или р': 'PF2E.TraitDescriptionModular',
    'монах': 'PF2E.TraitDescriptionMonk',
    'монах (оружие)': 'PF2E.TraitDescriptionMonkWeapon',
    'трансформация': 'PF2E.TraitDescriptionMorph',
    'стационарное': 'PF2E.TraitDescriptionMounted',
    'движение': 'PF2E.TraitDescriptionMove',
    'мультикласс': 'PF2E.TraitDescriptionMulticlass',
    'мутаген': 'PF2E.TraitDescriptionMutagen',
    'мутант': 'PF2E.TraitDescriptionMutant',
    'нагаджи': 'PF2E.TraitDescriptionNagaji',
    'некромантия': 'PF2E.TraitDescriptionNecromancy',
    'негативный': 'PF2E.TraitDescriptionNegative',
    'шумный': 'PF2E.TraitDescriptionNoisy',
    'несмертельное': 'PF2E.TraitDescriptionNonlethal',
    'нимфа': 'PF2E.TraitDescriptionNymph',
    'клятва': 'PF2E.TraitDescriptionOath',
    'оккультный': 'PF2E.TraitDescriptionOccult',
    'масло': 'PF2E.TraitDescriptionOil',
    'обонятельный': 'PF2E.TraitDescriptionOlfactory',
    'начальный': 'PF2E.TraitDescriptionOpen',
    'оракул': 'PF2E.TraitDescriptionOracle',
    'орк': 'PF2E.TraitDescriptionOrc',
    'ореад': 'PF2E.TraitDescriptionOread',
    'переполнение': 'PF2E.TraitDescriptionOverflow',
    'парирование': 'PF2E.TraitDescriptionParry',
    'растение': 'PF2E.TraitDescriptionPlant',
    'яд': 'PF2E.TraitDescriptionPoison',
    'полиморф': 'PF2E.TraitDescriptionPolymorph',
    'ponderous': 'PF2E.TraitDescriptionPonderous',
    'кукла': 'PF2E.TraitDescriptionPoppet',
    'переносное': 'PF2E.TraitDescriptionPortable',
    'позитивное': 'PF2E.TraitDescriptionPositive',
    'одержимость': 'PF2E.TraitDescriptionPossession',
    'зелье': 'PF2E.TraitDescriptionPotion',
    'драгоценный': 'PF2E.TraitDescriptionPrecious',
    'предсказание': 'PF2E.TraitDescriptionPrediction',
    'натиск': 'PF2E.TraitDescriptionPress',
    'природный': 'PF2E.TraitDescriptionPrimal',
    'перезарядка': 'PF2E.TraitDescriptionReload',
    'резонирующее': 'PF2E.TraitDescriptionResonant',
    'откровение': 'PF2E.TraitDescriptionRevelation',
    'плут': 'PF2E.TraitDescriptionRogue',
    'саггорак': 'PF2E.TraitDescriptionSaggorak',
    'разброс': 'PF2E.TraitDescriptionScatter',
    'свиток': 'PF2E.TraitDescriptionScroll',
    'видение': 'PF2E.TraitDescriptionScrying',
    'тайна': 'PF2E.TraitDescriptionSecret',
    'тень': 'PF2E.TraitDescriptionShadow',
    'шиск': 'PF2E.TraitDescriptionShisk',
    'шооны': 'PF2E.TraitDescriptionShoony',
    'толчок': 'PF2E.TraitDescriptionShove',
    'скелет': 'PF2E.TraitDescriptionSkeleton',
    'навык': 'PF2E.TraitDescriptionSkill',
    'сон': 'PF2E.TraitDescriptionSleep',
    'силок': 'PF2E.TraitDescriptionSnare',
    'публичный': 'PF2E.TraitDescriptionSocial',
    'звуковой': 'PF2E.TraitDescriptionSonic',
    'чародей': 'PF2E.TraitDescriptionSorcerer',
    'магический стрелок': 'PF2E.TraitDescriptionSpellgun',
    'сердце заклинания': 'PF2E.TraitDescriptionSpellheart',
    'брызги': 'PF2E.TraitDescriptionSplash',
    'брызги 10 фт': 'PF2E.TraitDescriptionSplash10',
    'дух': 'PF2E.TraitDescriptionSpirit',
    'спрайт': 'PF2E.TraitDescriptionSprite',
    'посох': 'PF2E.TraitDescriptionStaff',
    'стойка': 'PF2E.TraitDescriptionStance',
    'паровое': 'PF2E.TraitDescriptionSteam',
    'стрикс': 'PF2E.TraitDescriptionStrix',
    'строение': 'PF2E.TraitDescriptionStructure',
    'субъективная гравитация': 'PF2E.TraitDescriptionSubjectiveGravity',
    'сули': 'PF2E.TraitDescriptionSuli',
    'призванный': 'PF2E.TraitDescriptionSummoned',
    'призыватель': 'PF2E.TraitDescriptionSummoner',
    'сорвиголова': 'PF2E.TraitDescriptionSwashbuckler',
    'размах': 'PF2E.TraitDescriptionSweep',
    'сильф': 'PF2E.TraitDescriptionSylph',
    'талисман': 'PF2E.TraitDescriptionTalisman',
    'татуировка': 'PF2E.TraitDescriptionTattoo',
    'технология': 'PF2E.TraitDescriptionTech',
    'телепатия': 'PF2E.TraitDescriptionTelepathy',
    'телепортация': 'PF2E.TraitDescriptionTeleportation',
    'тэнгу': 'PF2E.TraitDescriptionTengu',
    'привязанное': 'PF2E.TraitDescriptionTethered',
    'тауматург': 'PF2E.TraitDescriptionThaumaturge',
    'метательное': 'PF2E.TraitDescriptionThrown',
    'тифлинг': 'PF2E.TraitDescriptionTiefling',
    'трансмутация': 'PF2E.TraitDescriptionTransmutation',
    'ловушка': 'PF2E.TraitDescriptionTrap',
    'опрокидывание': 'PF2E.TraitDescriptionTrip',
    'истинное имя': 'PF2E.TraitDescriptionTrueName',
    'парное': 'PF2E.TraitDescriptionTwin',
    'двуручное': 'PF2E.TraitDescriptionTwoHand',
    'безоружное': 'PF2E.TraitDescriptionUnarmed',
    'необычный': 'PF2E.TraitDescriptionUncommon',
    'ундина': 'PF2E.TraitDescriptionUndine',
    'уникальный': 'PF2E.TraitDescriptionUnique',
    'нестабильный': 'PF2E.TraitDescriptionUnstable',
    'вампир': 'PF2E.TraitDescriptionVampire',
    'ванара': 'PF2E.TraitDescriptionVanara',
    'vehicular': 'PF2E.TraitDescriptionVehicular',
    'универсальное': 'PF2E.TraitDescriptionVersatile',
    'вирулентный': 'PF2E.TraitDescriptionVirulent',
    'вишканья': 'PF2E.TraitDescriptionVishkanya',
    'визуальный': 'PF2E.TraitDescriptionVisual',
    'жизненность': 'PF2E.TraitDescriptionVitality',
    'пустота': 'PF2E.TraitDescriptionVoid',
    'залповое': 'PF2E.TraitDescriptionVolley',
    'волшебная палочка': 'PF2E.TraitDescriptionWand',
    'вода': 'PF2E.TraitDescriptionWater',
    'ваян': 'PF2E.TraitDescriptionWayang',
    'оружие': 'PF2E.TraitDescriptionWeapons',
    'оборотень': 'PF2E.TraitDescriptionWerecreature',
    'умертвие': 'PF2E.TraitDescriptionWight',
    'ведьма': 'PF2E.TraitDescriptionWitch',
    'волшебник': 'PF2E.TraitDescriptionWizard',
    'дерево': 'PF2E.TraitDescriptionWood',
      // Добавьте другие слова и их описания здесь
  };

  // Общий класс для всех слов
  const commonClass = 'paizo-style tag tooltipstered';

  // Перебираем текстовые элементы и заменяем слова
  element.each((index, el) => {
      const text = $(el).html();

      // Заменяем слова внутри `` и оставляем `` внутри оформления
      const replacedText = text.replace(/`([^`]+)`/g, (match, content) => {
          const description = wordMappings[content.toLowerCase()];
          if (description) {
              // Если слово найдено в mapping, заменяем его на соответствующий HTML код
              return `<span class="${commonClass}" data-trait="" data-description="${description}">\`${content}\`</span>`;
          } else {
              // Возвращаем исходное слово внутри ``, если оно не найдено в mapping
              return `\`${content}\``;
          }
      });

      // Заменяем исходный текст на измененный
      $(el).html(replacedText);
  });
}
